2017-03-23 21:41:36,650 T244 INFO 已进入函数。。。。
2017-03-23 21:41:36,660 T244 INFO 用户【manager】登录
2017-03-23 21:41:36,668 T244 INFO 用户名或密码码输入错误
2017-03-23 21:45:30,918 T28848 INFO 已进入函数。。。。
2017-03-23 21:45:30,921 T28848 INFO 用户【kgdl】登录
2017-03-23 21:45:30,927 T28848 INFO 用户名或密码码输入错误
2017-03-23 21:54:03,743 T18416 INFO 已进入函数。。。。
2017-03-23 21:54:03,747 T18416 INFO 用户【kdgl】登录
2017-03-23 21:54:03,801 T18416 INFO 把用户名与密码存放到session中，用于之后的判断用户是否登陆
2017-03-23 21:54:03,825 T18416 INFO 会话session：【<WSGIRequest
path:/login_up/,
GET:<QueryDict: {}>,
POST:<QueryDict: {u'username': [u'kdgl'], u'password': [u'kdgl']}>,
COOKIES:{'csrftoken': 'i5i5eon5cQaqxZaylIzHBizGAY5tr3We',
 'sessionid': '7b1b4360a04ca42e0c9ff831c57c7df3'},
META:{'#ENVTSLOGSHELLEXT17168': '267391792',
 'ALLUSERSPROFILE': 'C:\\ProgramData',
 'APPDATA': 'C:\\Users\\chengdegong\\AppData\\Roaming',
 'CATALINA_HOME': 'E:\\apache-tomcat-7.0.37',
 'CLASSPATH': '.;E:\\JDK\\jdk1.7.0_25\\bin;\\lib;E:\\JDK\\jdk1.7.0_25\\bin;\\lib\\tools.jar;E:\\apache-tomcat-7.0.37\\lib;',
 'COMMONPROGRAMFILES': 'C:\\Program Files\\Common Files',
 'COMMONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files',
 'COMMONPROGRAMW6432': 'C:\\Program Files\\Common Files',
 'COMPUTERNAME': 'LAPTOP-L836I1L2',
 'COMSPEC': 'C:\\WINDOWS\\system32\\cmd.exe',
 'CONFIGSETROOT': 'C:\\WINDOWS\\ConfigSetRoot',
 'CONTENT_LENGTH': '27',
 'CONTENT_TYPE': 'application/x-www-form-urlencoded;charset=UTF-8',
 'DJANGO_SETTINGS_MODULE': 'zjyw.settings',
 'EASYPLUSSDK': '"C:\\Program Files (x86)\\Common Files\\lenovo\\easyplussdk\\bin"',
 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer',
 'FPS_BROWSER_USER_PROFILE_STRING': 'Default',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HOMEDRIVE': 'C:',
 'HOMEPATH': '\\Users\\chengdegong',
 'HTTP_ACCEPT': 'application/json, text/javascript, */*; q=0.01',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'zh-CN,zh;q=0.8',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_COOKIE': 'csrftoken=i5i5eon5cQaqxZaylIzHBizGAY5tr3We; sessionid=7b1b4360a04ca42e0c9ff831c57c7df3',
 'HTTP_HOST': '127.0.0.1:8080',
 'HTTP_ORIGIN': 'http://127.0.0.1:8080',
 'HTTP_REFERER': 'http://127.0.0.1:8080/',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36',
 'HTTP_X_CSRFTOKEN': 'i5i5eon5cQaqxZaylIzHBizGAY5tr3We',
 'HTTP_X_REQUESTED_WITH': 'XMLHttpRequest',
 'JAVA_HOME': 'E:\\JDK\\jdk1.7.0_25\\bin;',
 'LOCALAPPDATA': 'C:\\Users\\chengdegong\\AppData\\Local',
 'LOGONSERVER': '\\\\LAPTOP-L836I1L2',
 'NLS_CHARACTERSET': 'AL32UTF8',
 'NLS_LANG': 'AMERICAN_AMERICA.AL32UTF8',
 'NUMBER_OF_PROCESSORS': '8',
 'OS': 'Windows_NT',
 'PATH': 'E:\\JDK\\jdk1.7.0_25\\bin;E:\\apache-tomcat-7.0.37\\bin;C:\\Perl64\\site\\bin;C:\\Perl64\\bin;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Program Files (x86)\\Lenovo\\FusionEngine;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\Common Files\\lenovo\\easyplussdk\\bin;C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\TortoiseSVN\\bin;E:\\Python27;E:\\Python34;E:\\pgsql\\bin;E:\\emeditor;E:\\hg\\djangoext;E:\\hg\\shangjie;E:\\oracle;E:\\Chrome\\chrome.exe;E:\\Program Files (x86)\\ATT\\Graphviz\\bin;E:\\Program Files (x86)\\ATT\\Graphviz\\bin\\tools;C:\\PROGRA~2\\ATT\\Graphviz\\bin;C:\\PROGRA~2\\ATT\\Graphviz\\bin\\tools;E:\\hg_build\\;E:\\Python26\\Scripts;C:\\Program Files\\MySQL\\MySQL Server 5.6\\bin;E:\\Python27\\Scripts;E:\\Python27\\Lib\\site-packages\\django\\bin;E:\\Git\\cmd;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Program Files\\nodejs\\;E:\\git _view_tool\\bin;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Users\\chengdegong\\AppData\\Roaming\\npm',
 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY',
 'PATH_INFO': u'/login_up/',
 'PROCESSOR_ARCHITECTURE': 'AMD64',
 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 94 Stepping 3, GenuineIntel',
 'PROCESSOR_LEVEL': '6',
 'PROCESSOR_REVISION': '5e03',
 'PROGRAMDATA': 'C:\\ProgramData',
 'PROGRAMFILES': 'C:\\Program Files',
 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)',
 'PROGRAMW6432': 'C:\\Program Files',
 'PROMPT': '$P$G',
 'PSMODULEPATH': 'C:\\WINDOWS\\system32\\WindowsPowerShell\\v1.0\\Modules\\',
 'PUBLIC': 'C:\\Users\\Public',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_HOST': 'LAPTOP-L836I1L2',
 'REQUEST_METHOD': 'POST',
 'RUN_MAIN': 'true',
 'SCRIPT_NAME': u'',
 'SERVER_NAME': 'LAPTOP-L836I1L2',
 'SERVER_PORT': '8080',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.1 Python/2.7',
 'SESSIONNAME': 'Console',
 'SYSTEMDRIVE': 'C:',
 'SYSTEMROOT': 'C:\\WINDOWS',
 'TEMP': 'C:\\Users\\CHENGD~1\\AppData\\Local\\Temp',
 'TMP': 'C:\\Users\\CHENGD~1\\AppData\\Local\\Temp',
 'USERDOMAIN': 'LAPTOP-L836I1L2',
 'USERDOMAIN_ROAMINGPROFILE': 'LAPTOP-L836I1L2',
 'USERNAME': 'chengdegong',
 'USERPROFILE': 'C:\\Users\\chengdegong',
 'WINDIR': 'C:\\WINDOWS',
 'wsgi.errors': <open file '<stderr>', mode 'w' at 0x00000000024C71E0>,
 'wsgi.file_wrapper': <class wsgiref.util.FileWrapper at 0x0000000003392A68>,
 'wsgi.input': <socket._fileobject object at 0x00000000040004F8>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': True,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}>】
2017-03-23 21:54:06,066 T18416 INFO 用户【kdgl】登录验证成功
2017-03-23 21:54:06,109 T50704 INFO 来自session的用户名：kdgl
2017-03-23 21:54:06,144 T50704 ERROR 后台函数[login_view]执行错误:(1146, "Table 'kdgl.agentinfo' doesn't exist")
Traceback (most recent call last):
  File "F:\zjyw\src\oa\views.py", line 100, in main_view
    rs = myapi.sql_execute(cur, sql)
  File "F:\zjyw\src\zjyw_utils\utils.py", line 172, in sql_execute
    return ResultSet( cur , sql , params , encoding )
  File "F:\zjyw\src\zjyw_utils\utils.py", line 192, in __init__
    self.__cursor.execute( sql )
  File "E:\Python27\lib\site-packages\MySQLdb\cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "E:\Python27\lib\site-packages\MySQLdb\connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
          errorclass = <class '_mysql_exceptions.ProgrammingError'>
          errorvalue = ProgrammingError(1146, "Table 'kdgl.agentinfo' doesn't exist")
               error = (<class '_mysql_exceptions.ProgrammingError'>, ProgrammingError(1146, "Table 'kdgl.agentinfo' doesn't exist"))
ProgrammingError: (1146, "Table 'kdgl.agentinfo' doesn't exist")
2017-03-23 21:55:32,979 T32340 INFO 来自session的用户名：kdgl
2017-03-23 21:55:32,989 T32340 ERROR 后台函数[login_view]执行错误:(1146, "Table 'kdgl.agentinfo' doesn't exist")
Traceback (most recent call last):
  File "F:\zjyw\src\oa\views.py", line 100, in main_view
    rs = myapi.sql_execute(cur, sql)
  File "F:\zjyw\src\zjyw_utils\utils.py", line 172, in sql_execute
    return ResultSet( cur , sql , params , encoding )
  File "F:\zjyw\src\zjyw_utils\utils.py", line 192, in __init__
    self.__cursor.execute( sql )
  File "E:\Python27\lib\site-packages\MySQLdb\cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "E:\Python27\lib\site-packages\MySQLdb\connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
          errorclass = <class '_mysql_exceptions.ProgrammingError'>
          errorvalue = ProgrammingError(1146, "Table 'kdgl.agentinfo' doesn't exist")
               error = (<class '_mysql_exceptions.ProgrammingError'>, ProgrammingError(1146, "Table 'kdgl.agentinfo' doesn't exist"))
ProgrammingError: (1146, "Table 'kdgl.agentinfo' doesn't exist")
2017-03-23 21:55:34,395 T44580 INFO 来自session的用户名：kdgl
2017-03-23 21:55:34,404 T44580 ERROR 后台函数[login_view]执行错误:(1146, "Table 'kdgl.agentinfo' doesn't exist")
Traceback (most recent call last):
  File "F:\zjyw\src\oa\views.py", line 100, in main_view
    rs = myapi.sql_execute(cur, sql)
  File "F:\zjyw\src\zjyw_utils\utils.py", line 172, in sql_execute
    return ResultSet( cur , sql , params , encoding )
  File "F:\zjyw\src\zjyw_utils\utils.py", line 192, in __init__
    self.__cursor.execute( sql )
  File "E:\Python27\lib\site-packages\MySQLdb\cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "E:\Python27\lib\site-packages\MySQLdb\connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
          errorclass = <class '_mysql_exceptions.ProgrammingError'>
          errorvalue = ProgrammingError(1146, "Table 'kdgl.agentinfo' doesn't exist")
               error = (<class '_mysql_exceptions.ProgrammingError'>, ProgrammingError(1146, "Table 'kdgl.agentinfo' doesn't exist"))
ProgrammingError: (1146, "Table 'kdgl.agentinfo' doesn't exist")
2017-03-23 21:55:34,875 T21712 INFO 来自session的用户名：kdgl
2017-03-23 21:55:34,881 T21712 ERROR 后台函数[login_view]执行错误:(1146, "Table 'kdgl.agentinfo' doesn't exist")
Traceback (most recent call last):
  File "F:\zjyw\src\oa\views.py", line 100, in main_view
    rs = myapi.sql_execute(cur, sql)
  File "F:\zjyw\src\zjyw_utils\utils.py", line 172, in sql_execute
    return ResultSet( cur , sql , params , encoding )
  File "F:\zjyw\src\zjyw_utils\utils.py", line 192, in __init__
    self.__cursor.execute( sql )
  File "E:\Python27\lib\site-packages\MySQLdb\cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "E:\Python27\lib\site-packages\MySQLdb\connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
          errorclass = <class '_mysql_exceptions.ProgrammingError'>
          errorvalue = ProgrammingError(1146, "Table 'kdgl.agentinfo' doesn't exist")
               error = (<class '_mysql_exceptions.ProgrammingError'>, ProgrammingError(1146, "Table 'kdgl.agentinfo' doesn't exist"))
ProgrammingError: (1146, "Table 'kdgl.agentinfo' doesn't exist")
2017-03-23 21:56:04,918 T33736 INFO 来自session的用户名：kdgl
2017-03-23 21:56:04,927 T33736 ERROR 后台函数[login_view]执行错误:(1146, "Table 'kdgl.agentinfo' doesn't exist")
Traceback (most recent call last):
  File "F:\zjyw\src\oa\views.py", line 100, in main_view
    rs = myapi.sql_execute(cur, sql)
  File "F:\zjyw\src\zjyw_utils\utils.py", line 172, in sql_execute
    return ResultSet( cur , sql , params , encoding )
  File "F:\zjyw\src\zjyw_utils\utils.py", line 192, in __init__
    self.__cursor.execute( sql )
  File "E:\Python27\lib\site-packages\MySQLdb\cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "E:\Python27\lib\site-packages\MySQLdb\connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
          errorclass = <class '_mysql_exceptions.ProgrammingError'>
          errorvalue = ProgrammingError(1146, "Table 'kdgl.agentinfo' doesn't exist")
               error = (<class '_mysql_exceptions.ProgrammingError'>, ProgrammingError(1146, "Table 'kdgl.agentinfo' doesn't exist"))
ProgrammingError: (1146, "Table 'kdgl.agentinfo' doesn't exist")
2017-03-23 21:56:05,908 T55028 INFO 来自session的用户名：kdgl
2017-03-23 21:56:05,917 T55028 ERROR 后台函数[login_view]执行错误:(1146, "Table 'kdgl.agentinfo' doesn't exist")
Traceback (most recent call last):
  File "F:\zjyw\src\oa\views.py", line 100, in main_view
    rs = myapi.sql_execute(cur, sql)
  File "F:\zjyw\src\zjyw_utils\utils.py", line 172, in sql_execute
    return ResultSet( cur , sql , params , encoding )
  File "F:\zjyw\src\zjyw_utils\utils.py", line 192, in __init__
    self.__cursor.execute( sql )
  File "E:\Python27\lib\site-packages\MySQLdb\cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "E:\Python27\lib\site-packages\MySQLdb\connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
          errorclass = <class '_mysql_exceptions.ProgrammingError'>
          errorvalue = ProgrammingError(1146, "Table 'kdgl.agentinfo' doesn't exist")
               error = (<class '_mysql_exceptions.ProgrammingError'>, ProgrammingError(1146, "Table 'kdgl.agentinfo' doesn't exist"))
ProgrammingError: (1146, "Table 'kdgl.agentinfo' doesn't exist")
2017-03-23 21:57:10,177 T43048 INFO 来自session的用户名：kdgl
2017-03-23 21:57:10,184 T43048 ERROR 后台函数[login_view]执行错误:(1146, "Table 'kdgl.agentinfo' doesn't exist")
Traceback (most recent call last):
  File "F:\zjyw\src\oa\views.py", line 100, in main_view
    rs = myapi.sql_execute(cur, sql)
  File "F:\zjyw\src\zjyw_utils\utils.py", line 172, in sql_execute
    return ResultSet( cur , sql , params , encoding )
  File "F:\zjyw\src\zjyw_utils\utils.py", line 192, in __init__
    self.__cursor.execute( sql )
  File "E:\Python27\lib\site-packages\MySQLdb\cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "E:\Python27\lib\site-packages\MySQLdb\connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
          errorclass = <class '_mysql_exceptions.ProgrammingError'>
          errorvalue = ProgrammingError(1146, "Table 'kdgl.agentinfo' doesn't exist")
               error = (<class '_mysql_exceptions.ProgrammingError'>, ProgrammingError(1146, "Table 'kdgl.agentinfo' doesn't exist"))
ProgrammingError: (1146, "Table 'kdgl.agentinfo' doesn't exist")
2017-03-23 22:01:59,839 T47640 INFO 来自session的用户名：kdgl
2017-03-23 22:01:59,848 T47640 ERROR 后台函数[login_view]执行错误:(1146, "Table 'kdgl.agentinfo' doesn't exist")
Traceback (most recent call last):
  File "F:\zjyw\src\oa\views.py", line 100, in main_view
    rs = myapi.sql_execute(cur, sql)
  File "F:\zjyw\src\zjyw_utils\utils.py", line 172, in sql_execute
    return ResultSet( cur , sql , params , encoding )
  File "F:\zjyw\src\zjyw_utils\utils.py", line 192, in __init__
    self.__cursor.execute( sql )
  File "E:\Python27\lib\site-packages\MySQLdb\cursors.py", line 174, in execute
    self.errorhandler(self, exc, value)
  File "E:\Python27\lib\site-packages\MySQLdb\connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
          errorclass = <class '_mysql_exceptions.ProgrammingError'>
          errorvalue = ProgrammingError(1146, "Table 'kdgl.agentinfo' doesn't exist")
               error = (<class '_mysql_exceptions.ProgrammingError'>, ProgrammingError(1146, "Table 'kdgl.agentinfo' doesn't exist"))
ProgrammingError: (1146, "Table 'kdgl.agentinfo' doesn't exist")
